"""
Fix Generator — turns failure patterns into code changes.

When Overwatch identifies a recurring failure with a known code-level fix,
this module generates the actual file changes and (via aria_repo.create_fix_pr)
opens a PR on aria-platform.

The fix templates here are seeded from real incidents Overwatch has
already encountered. Each template is conservative — small, targeted
changes with clear preconditions, suitable for autonomous PR creation.
"""
from __future__ import annotations

import logging
import re
from typing import Any

from nexus.forge.aria_repo import FileChange, create_fix_pr, read_file

logger = logging.getLogger("nexus.forge.fix_generator")


# Fix templates seeded from real failures Overwatch has seen.
# Each template is keyed by FailurePattern.name and produces FileChanges.
_TEMPLATES: dict[str, dict[str, Any]] = {
    "bedrock_json_parse": {
        "title": "fix(quality_gate): strip markdown fences before JSON parse",
        "body": (
            "Bedrock occasionally wraps JSON responses in markdown fences "
            "(```json … ```), causing parse failures. This fix strips "
            "leading/trailing fences before attempting `json.loads`.\n\n"
            "Generated by Overwatch from FailurePattern `bedrock_json_parse`."
        ),
        "branch": "overwatch/fix-bedrock-fence-stripping",
        "files": [
            {
                "path": "aria/intelligence/quality_gate.py",
                "marker": "json.loads(",
                "transform": "fence_strip",
            }
        ],
    },
    "bare_aws_to_module": {
        "title": "fix(ci): replace bare `aws` with `python3 -m awscli`",
        "body": (
            "GitHub Actions runners do not always have a top-level `aws` "
            "binary on PATH, but they do have the awscli Python package. "
            "Use `python3 -m awscli` for portability.\n\n"
            "Generated by Overwatch from FailurePattern `bare_aws_to_module`."
        ),
        "branch": "overwatch/fix-aws-cli-module-call",
        "files": [
            {
                "path": ".github/workflows/deploy.yml",
                "marker": "aws ",
                "transform": "replace_bare_aws",
            }
        ],
    },
    "github_app_owner_match": {
        "title": "fix(github_app): verify installation owner matches tenant",
        "body": (
            "When a tenant connects a private repo, the GitHub App "
            "installation lookup must match the repo owner exactly. This "
            "fix adds an owner-equality check before attempting any push.\n\n"
            "Generated by Overwatch from FailurePattern `github_app_owner_match`."
        ),
        "branch": "overwatch/fix-github-app-owner-check",
        "files": [
            {
                "path": "aria/customer/github_app.py",
                "marker": "installation",
                "transform": "owner_match_guard",
            }
        ],
    },
}


def _apply_transform(transform: str, original: str, marker: str) -> str | None:
    """
    Apply a named transform to a file's contents. Returns the new content,
    or None if the transform doesn't apply (no marker found, etc.).
    """
    if marker not in original:
        return None
    if transform == "fence_strip":
        # Insert a defensive helper, then wrap the json.loads(...) argument
        # in _strip_fences(...). Uses a regex to keep parens balanced.
        helper = (
            "def _strip_fences(text):\n"
            "    text = text.strip()\n"
            "    if text.startswith('```'):\n"
            "        text = text.split('\\n', 1)[-1]\n"
            "    if text.endswith('```'):\n"
            "        text = text.rsplit('```', 1)[0]\n"
            "    return text.strip()\n\n"
        )
        if "_strip_fences" in original:
            return None  # already applied
        # Match `json.loads(<simple_expr>)` — only single-argument calls
        # without nested parens. This is intentionally conservative.
        wrapped = re.sub(
            r"json\.loads\(([^()]+)\)",
            r"json.loads(_strip_fences(\1))",
            original,
        )
        if wrapped == original:
            return None  # nothing matched the simple form
        return helper + wrapped
    if transform == "replace_bare_aws":
        return original.replace(" aws ", " python3 -m awscli ")
    if transform == "owner_match_guard":
        guard = (
            "    if installation.account.login != repo_owner:\n"
            "        raise PermissionError('installation owner mismatch')\n"
        )
        if "installation owner mismatch" in original:
            return None
        return original.replace("installation = ", guard + "    installation = ", 1)
    return None


def generate_fix(pattern_name: str) -> list[FileChange]:
    """
    Build the FileChange list for a known FailurePattern. Returns []
    if no template exists or none of the templates' preconditions match.
    """
    template = _TEMPLATES.get(pattern_name)
    if not template:
        return []
    changes: list[FileChange] = []
    for spec in template["files"]:
        original = read_file(spec["path"]) or ""
        new_content = _apply_transform(spec["transform"], original, spec["marker"])
        if new_content is None or new_content == original:
            logger.info("fix template %s: precondition not met for %s", pattern_name, spec["path"])
            continue
        changes.append(FileChange(path=spec["path"], new_content=new_content, old_content=original))
    return changes


def validate_fix(file_changes: list[FileChange]) -> tuple[bool, str]:
    """Quick sanity checks before opening a PR."""
    if not file_changes:
        return False, "no changes to apply"
    for change in file_changes:
        if not change.path or not change.new_content:
            return False, f"empty change for {change.path}"
        if change.old_content is not None and change.old_content == change.new_content:
            return False, f"no-op change for {change.path}"
    return True, "ok"


def propose_fix(pattern_name: str) -> dict[str, Any]:
    """
    Full pipeline: generate → validate → open PR. Returns the PR result
    dict from create_fix_pr, or {error: ...} if any step fails.
    """
    template = _TEMPLATES.get(pattern_name)
    if not template:
        return {"error": "unknown_pattern", "pattern": pattern_name}
    changes = generate_fix(pattern_name)
    ok, reason = validate_fix(changes)
    if not ok:
        return {"error": "validation_failed", "reason": reason, "pattern": pattern_name}
    return create_fix_pr(
        branch_name=template["branch"],
        file_changes=changes,
        title=template["title"],
        body=template["body"],
    )


def list_known_fix_templates() -> list[dict[str, str]]:
    """Surface the catalog of fix templates Overwatch can generate."""
    return [
        {"pattern": name, "title": tpl["title"], "branch": tpl["branch"]}
        for name, tpl in _TEMPLATES.items()
    ]
